### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by csphere** [TylerDM/OrangePeel#2]
https://github.com/FireflyX/OrangePeel/blob/master/OrangePeelTest/Car.cs

This looks all wonky on GH due to tab/space mix.

**Comment by csphere** [comment]
Strange bc [this](https://github.com/FireflyX/OrangePeel/blob/d9bb205b8db4e129f60d8a888d9fd31a0f03a02b/.editorconfig#L5) exists...

**Comment by TylerDM** [comment]
I added that file after the fact.  So I guess VS wound up doing half and half.
